// Generates src/render/widths.js from anafanafo's font width tables (CC0).
// Run once after `npm install`: node scripts/build-widths.mjs
// We keep only code points <= 0x2FFF (Latin, Greek, Cyrillic, punctuation,
// symbols); everything else (CJK, Hangul, emoji) is handled by rules in
// measure.js, which keeps the Worker bundle small.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);

const LIMIT = 0x2fff;
const fonts = {
  verdana11: "verdana-11px-normal",
  verdana10: "verdana-10px-normal",
  verdana10b: "verdana-10px-bold",
  helvetica11b: "helvetica-11px-bold",
};

let out = "// GENERATED by scripts/build-widths.mjs from anafanafo (CC0). Do not edit.\n";
out += "// Format: flat array of [lo, hi, width] triples, code points <= 0x2FFF.\n";
for (const [name, file] of Object.entries(fonts)) {
  const path = require.resolve(`anafanafo/data/${file}.json`);
  const data = JSON.parse(readFileSync(path, "utf8")).filter(([lo]) => lo <= LIMIT);
  const flat = data.flatMap(([lo, hi, w]) => [lo, hi, w]);
  out += `export const ${name} = ${JSON.stringify(flat)};\n`;
}
writeFileSync(new URL("../src/render/widths.js", import.meta.url), out);
console.log("wrote src/render/widths.js", out.length, "bytes");
