export default {
  name: "es",
  title: "Español",
  emoji: "🇪🇸",
  lang: "es",
  description: "Un mensaje corto y amable cada día, en español.",
  kind: "rotating",
  messages: [
    "Hoy también lo estás haciendo bien",
    "Paso a paso también se llega",
    "Hecho vale más que perfecto",
    "Empieza antes de estar listo",
    "Tómate un vaso de agua",
    "Descansar también es avanzar",
    "Un commit al día mantiene el caos a raya",
    "Nunca es tarde para empezar",
    "Ve a tu ritmo, pero ve",
    "Los errores son registros, no sentencias",
    "Escribe una línea. Luego otra.",
    "Respira hondo y vuelve a intentarlo",
    "Hoy va a ser un buen día",
    "Gracias por pasar por aquí",
    "Pregunta; preguntar es de valientes",
    "Come antes de programar",
    "Estira un poco, tu espalda te lo agradecerá",
    "No tienes que hacerlo todo solo",
    "Refactorizar es un acto de amor",
    "Si el plan falla, ajusta el plan",
    "Hay bugs que se arreglan con un paseo",
    "Dormir bien es productividad",
    "Deja una nota para tu yo de mañana",
    "Tu código ayuda a alguien",
    "Aprender una cosa hoy ya es suficiente",
    "Despliega con una sonrisa",
    "A veces hay que cerrar sesión",
    "Que tu café esté especialmente rico hoy",
    "Constancia mata talento",
    "Estás más cerca de lo que crees",
    "Descansa poco, avanza mucho",
    "Celebra las pequeñas victorias",
    "Tu esfuerzo cuenta, aunque no se vea",
    "Hoy es buen día para intentarlo",
    "Sé amable contigo mismo",
    "Menos pestañas, más foco",
    "Escribir es pensar en voz alta",
    "Eres suficiente, tal como eres",
    "Un buen comienzo es medio camino",
    "¡Ánimo, que tú puedes!",
  ],
};
