export default {
  name: "fr",
  title: "Français",
  emoji: "🇫🇷",
  lang: "fr",
  description: "Un petit message bienveillant chaque jour, en français.",
  kind: "rotating",
  messages: [
    "Tu t'en sors mieux que tu ne le penses",
    "Un petit pas reste un pas",
    "Fait vaut mieux que parfait",
    "Commence avant d'être prêt",
    "Bois un verre d'eau",
    "Se reposer, c'est aussi avancer",
    "Un commit par jour éloigne le chaos",
    "Il n'est jamais trop tard pour commencer",
    "Va à ton rythme, mais avance",
    "Les erreurs sont des logs, pas des verdicts",
    "Écris une ligne. Puis une autre.",
    "Respire un grand coup et réessaie",
    "Aujourd'hui sera une belle journée",
    "Merci d'être passé par ici",
    "Poser une question, c'est du courage",
    "Mange avant de coder",
    "Étire-toi, ton dos te dira merci",
    "Tu n'es pas obligé de tout faire seul",
    "Refactorer, c'est un acte d'amour",
    "Si le plan échoue, change le plan",
    "Certains bugs se règlent en marchant",
    "Bien dormir, c'est productif",
    "Laisse un mot à toi de demain",
    "Ton code aide quelqu'un",
    "Apprendre une chose aujourd'hui suffit",
    "Déploie avec le sourire",
    "Parfois, il faut se déconnecter",
    "Que ton café soit délicieux aujourd'hui",
    "La constance bat le talent",
    "Tu es plus près que tu ne le crois",
    "Repose-toi peu, avance beaucoup",
    "Célèbre les petites victoires",
    "Tes efforts comptent, même invisibles",
    "C'est un bon jour pour essayer",
    "Sois doux avec toi-même",
    "Moins d'onglets, plus de concentration",
    "Écrire, c'est penser à voix haute",
    "Tu es suffisant, tel que tu es",
    "Bien commencer, c'est la moitié du chemin",
    "Courage, tu peux le faire !",
  ],
};
