export default {
  name: "motivation",
  title: "Motivation",
  emoji: "🔥",
  lang: "en",
  description: "A short push for the day — no platitudes, just momentum.",
  kind: "rotating",
  messages: [
    "Start before you're ready",
    "Small steps still count as steps",
    "Done today beats perfect someday",
    "You've survived 100% of your worst days",
    "Progress, not perfection",
    "One page. One rep. One commit.",
    "Momentum is built, not found",
    "Do the thing you're avoiding first",
    "Future you is watching. Make them proud.",
    "Show up. That's most of it.",
    "Slow is smooth, smooth is fast",
    "Discipline is choosing later over now",
    "Ship it, then improve it",
    "Your pace is still a pace",
    "Rest is part of the plan",
    "Finish something small today",
    "Doubt is loud. Work is louder.",
    "Be the person you needed last year",
    "Today's effort is tomorrow's ease",
    "Don't break the chain",
    "Make it exist, then make it good",
    "The hard part is starting. Start.",
    "You're closer than you were yesterday",
    "Consistency beats intensity",
    "Do it scared",
    "Ten minutes counts",
    "Trade 'someday' for 'today'",
    "Plant the seed. Water it tomorrow too.",
    "You can do hard things",
    "Boring habits, remarkable results",
    "Aim for one honest hour",
    "Curiosity over pressure",
    "It's not too late. It never was.",
    "Keep the promise you made to yourself",
    "Tiny wins compound",
    "Focus on the next right step",
    "Effort is never wasted",
    "Reset. Refocus. Resume.",
    "Fall in love with the process",
    "What would make today count?",
    "Do less, but do it fully",
    "Courage is a muscle. Train it.",
    "Good enough today, better tomorrow",
    "The best time to begin is now",
    "Outwork your excuses",
    "Choose the harder right",
    "Every expert was once a beginner",
    "Start where you are, use what you have",
    "Deep breath. Then go.",
    "Leave it better than you found it",
    "Your future is built in ordinary hours",
    "Protect your focus like it's gold",
    "One brave email. One honest ask.",
    "Make today slightly better than yesterday",
    "You don't need permission to begin",
    "Learn it. Do it. Teach it.",
    "Being stuck is a signal, not a verdict",
    "Keep going — quietly, stubbornly",
    "Great work is mostly showing up again",
    "Today is a good day to try",
  ],
};
