export default {
  name: "productivity",
  title: "Productivity",
  emoji: "⏱️",
  lang: "en",
  description: "One practical, tested productivity tip a day.",
  kind: "rotating",
  messages: [
    "Two-minute rule: if it's quick, do it now",
    "Write tomorrow's top three before you log off",
    "Batch your notifications, not your focus",
    "Eat the frog: hardest task first",
    "One tab at a time. Seriously.",
    "Timebox it: 25 on, 5 off",
    "Say no to protect your yes",
    "A messy draft beats a blank page",
    "Decide once, then automate",
    "Close the loop: reply, file, or delete",
    "Start with the smallest possible version",
    "Meetings need an agenda or they need cancelling",
    "Put the phone in another room",
    "Do the deep work before noon",
    "Define 'done' before you start",
    "Track time for a week; it will surprise you",
    "If it takes three tries, write it down",
    "Rest is a productivity tool",
    "Parkinson's law: shrink the deadline",
    "Review your week every Friday",
    "Leave a note for future-you at day's end",
    "Group errands, calls, and admin into one block",
    "Progress log beats to-do list",
    "Single-task; multitasking is task-switching",
    "Reduce decisions: same breakfast, same start",
    "Read the ticket twice, write once",
    "Set a stopping time and honour it",
    "Ask: what happens if I just don't?",
    "Turn the recurring question into a checklist",
    "Ship the 80% and gather feedback",
    "Name the next physical action",
    "Inbox zero is optional; inbox calm isn't",
    "Say 'let me get back to you' more often",
    "Walk to think; sit to write",
    "Don't optimise what you should delete",
    "Learn one keyboard shortcut today",
    "If it's not on the calendar, it's not real",
    "Break big tasks until one feels easy",
    "Take notes on what you got wrong",
    "Energy management beats time management",
  ],
};
