export default {
  name: "pt",
  title: "Português",
  emoji: "🇧🇷",
  lang: "pt",
  description: "Uma mensagem curta e gentil por dia, em português.",
  kind: "rotating",
  messages: [
    "Você está indo melhor do que pensa",
    "Um passo pequeno ainda é um passo",
    "Feito é melhor que perfeito",
    "Comece antes de estar pronto",
    "Beba um copo d'água",
    "Descansar também é avançar",
    "Um commit por dia afasta o caos",
    "Nunca é tarde para começar",
    "Vá no seu ritmo, mas vá",
    "Erros são logs, não sentenças",
    "Escreva uma linha. Depois outra.",
    "Respire fundo e tente de novo",
    "Hoje vai ser um bom dia",
    "Obrigado por passar por aqui",
    "Perguntar é coragem",
    "Coma antes de programar",
    "Alongue-se, suas costas agradecem",
    "Você não precisa fazer tudo sozinho",
    "Refatorar é um ato de amor",
    "Se o plano falhar, ajuste o plano",
    "Tem bug que se resolve caminhando",
    "Dormir bem é produtividade",
    "Deixe um bilhete para o você de amanhã",
    "Seu código ajuda alguém",
    "Aprender uma coisa hoje já basta",
    "Faça o deploy sorrindo",
    "Às vezes é preciso fazer logout",
    "Que seu café esteja especialmente bom hoje",
    "Constância vence talento",
    "Você está mais perto do que imagina",
    "Descanse pouco, avance muito",
    "Comemore as pequenas vitórias",
    "Seu esforço conta, mesmo invisível",
    "Hoje é um bom dia para tentar",
    "Seja gentil com você mesmo",
    "Menos abas, mais foco",
    "Escrever é pensar em voz alta",
    "Você é suficiente, do jeito que é",
    "Bem começado é meio caminho andado",
    "Vai dar certo!",
  ],
};
