export default {
  name: "puns",
  title: "Puns",
  emoji: "🥁",
  lang: "en",
  description: "One groan-worthy pun per day. You've been warned.",
  kind: "rotating",
  messages: [
    "I'm reading a book on anti-gravity. Can't put it down.",
    "Why did the scarecrow win? Outstanding in his field.",
    "I used to be a banker. Then I lost interest.",
    "Time flies like an arrow; fruit flies like a banana",
    "I'd tell a chemistry joke but I'd get no reaction",
    "The past, present and future walked in. It was tense.",
    "I only know 25 letters of the alphabet. Don't know y.",
    "Parallel lines have so much in common. Shame they never meet.",
    "I'm on a seafood diet. I see food, I eat it.",
    "What's a skeleton's least favourite room? The living room.",
    "Broken pencils are pointless",
    "Velcro: what a rip-off",
    "Wondered all night where the sun went. Then it dawned on me.",
    "Never trust atoms. They make up everything.",
    "Why don't eggs tell jokes? They'd crack up.",
    "A boiled egg every morning is hard to beat",
    "The shovel was a ground-breaking invention",
    "Considered a brain transplant, then changed my mind",
    "What do you call a fake noodle? An impasta.",
    "Claustrophobics think best outside the box",
    "I told my computer I needed a break. It froze.",
    "Why was the math book sad? Too many problems.",
    "I ordered a chicken and an egg online. I'll let you know.",
    "The rotation of the Earth really makes my day",
    "I used to hate facial hair. Then it grew on me.",
    "The bicycle couldn't stand up. It was two-tired.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Cows have hooves because they lactose",
    "I'm reading about mazes. I got lost in it.",
    "A plateau is the highest form of flattery",
    "My calendar's days are numbered",
    "What's orange and sounds like a parrot? A carrot.",
    "Addicted to the hokey pokey? Turn yourself around.",
    "Atheism is a non-prophet organisation",
    "Elevators: they lift my spirits",
    "The cheese factory exploded. De brie everywhere.",
    "I'd agree with you, but then we'd both be wrong",
    "What do you call a sleeping dinosaur? A dino-snore.",
    "Whiteboards are remarkable",
    "The graveyard is so crowded people are dying to get in",
  ],
};
