export default {
  name: "science",
  title: "Science facts",
  emoji: "🔬",
  lang: "en",
  description: "A true, checkable science fact each day.",
  kind: "rotating",
  messages: [
    "Honey never spoils — edible after 3,000 years",
    "Octopuses have three hearts and blue blood",
    "Bananas are slightly radioactive (potassium-40)",
    "Your body has about 37 trillion cells",
    "A teaspoon of neutron star weighs ~a billion tonnes",
    "Water can boil and freeze at once (triple point)",
    "Hot water can freeze faster than cold (Mpemba effect)",
    "Sharks predate trees by ~50 million years",
    "Lightning is 5× hotter than the Sun's surface",
    "DNA from any human is 99.9% identical to yours",
    "Sound travels 4× faster in water than air",
    "Glass is a solid, not a slow liquid",
    "Superfluid helium climbs out of its container",
    "Wombat poop is cube-shaped",
    "Your stomach lining renews every few days",
    "Tardigrades survive the vacuum of space",
    "There are more trees on Earth than stars in the Milky Way",
    "A day on Venus is longer than its year",
    "The Eiffel Tower grows ~15 cm in summer heat",
    "Cats can't taste sweetness",
    "Diamonds and pencil lead are both pure carbon",
    "The human eye can spot a candle ~2.6 km away",
    "Sloths can hold their breath longer than dolphins",
    "Bacteria in you outnumber your own cells",
    "Light from the Sun takes 8 min 20 s to reach you",
    "Bees can recognise human faces",
    "Hot air rises because it's less dense, not lighter",
    "Rain has a smell: petrichor, made by soil bacteria",
    "An atom is 99.9999999% empty space",
    "Crows hold grudges and remember faces",
    "A cloud can weigh over a million kilograms",
    "The Pacific is wider than the Moon",
    "Cold water is denser — except ice, which floats",
    "Your bones are about 4× stronger than concrete",
    "Butterflies taste with their feet",
    "Time runs faster on a mountaintop (really)",
    "Mercury is the only metal liquid at room temperature",
    "Elephants can't jump. Neither can sloths.",
    "Red blood cells have no nucleus",
    "The speed of light is exactly 299,792,458 m/s",
    "Trees talk through fungal networks underground",
    "Space isn't cold — it's just empty",
    "Some frogs freeze solid in winter and thaw in spring",
    "A flea can jump 100× its height",
    "Your brain uses ~20% of your energy",
    "Snow is not white; it's transparent and scatters light",
    "Fingernails grow about 3.5 mm a month",
    "The heart beats ~100,000 times a day",
    "About half your genes have a banana counterpart",
    "Antarctica is the world's largest desert",
  ],
};
