export default {
  name: "space",
  title: "Space",
  emoji: "🪐",
  lang: "en",
  description: "A daily fact from beyond the atmosphere.",
  kind: "rotating",
  messages: [
    "Neutron stars can spin 700 times a second",
    "One day on Mercury lasts 59 Earth days",
    "Jupiter's Great Red Spot is bigger than Earth",
    "Saturn would float in a big enough bathtub",
    "The Moon is drifting away 3.8 cm a year",
    "Voyager 1 is over 24 billion km from home",
    "There's a diamond planet: 55 Cancri e",
    "Sunsets on Mars are blue",
    "Olympus Mons is 2.5× the height of Everest",
    "A year on Neptune is 165 Earth years",
    "The Sun holds 99.8% of the solar system's mass",
    "Footprints on the Moon will last millions of years",
    "Venus spins backwards",
    "It rains glass sideways on exoplanet HD 189733b",
    "The ISS orbits Earth every 90 minutes",
    "Light from Proxima Centauri took 4.2 years to arrive",
    "Uranus rotates on its side",
    "There are more stars than grains of sand on Earth",
    "The Sun's core is about 15 million °C",
    "Mars has two tiny moons: Phobos and Deimos",
    "Space smells like seared steak, say astronauts",
    "The Milky Way and Andromeda will collide in ~4.5 Gyr",
    "Titan has lakes — of liquid methane",
    "Pluto is smaller than Earth's Moon",
    "The Sun is a mid-sized, middle-aged star",
    "Betelgeuse is so big it would swallow Jupiter's orbit",
    "Black holes don't suck. They just have gravity.",
    "Jupiter has at least 95 moons",
    "Halley's Comet is back in 2061",
    "Astronauts grow ~5 cm taller in orbit",
    "Water ice exists on Mercury, in shadowed craters",
    "The universe is 13.8 billion years old",
    "Earth's core is as hot as the Sun's surface",
    "Ceres is the only dwarf planet in the asteroid belt",
    "Sagittarius A* weighs about 4 million Suns",
    "Saturn's rings are mostly water ice",
    "One million Earths would fit inside the Sun",
    "The Moon has moonquakes",
    "Io is the most volcanic body in the solar system",
    "Europa likely hides an ocean under its ice",
    "Sound can't travel through space — but light can",
    "Neptune's winds top 2,000 km/h",
    "Mars once had rivers and lakes",
    "The Hubble has taken over 1.5 million observations",
    "A spacesuit costs about $12 million",
    "The Kármán line marks space at 100 km up",
    "Enceladus shoots water geysers into space",
    "The Sun will become a red giant in ~5 billion years",
    "GPS satellites must correct for relativity",
    "You are made of star stuff",
  ],
};
