// Paraphrases of Marcus Aurelius, Seneca and Epictetus — all public domain.
export default {
  name: "stoic",
  title: "Stoic",
  emoji: "🏛️",
  lang: "en",
  description: "One Stoic reminder a day, from Marcus, Seneca and Epictetus.",
  kind: "rotating",
  messages: [
    "You have power over your mind, not events",
    "The obstacle is the way",
    "We suffer more in imagination than reality",
    "Waste no time arguing what a good person is. Be one.",
    "It's not things that upset us, but our judgments",
    "Confine yourself to the present",
    "Luck is preparation meeting opportunity",
    "Focus on what you control",
    "Begin at once to live",
    "Difficulties strengthen the mind",
    "How long will you wait to demand the best of yourself?",
    "No one can hurt you without your consent",
    "Don't explain your philosophy. Embody it.",
    "First say to yourself what you would be",
    "The best revenge is not to be like them",
    "Wealth is having few wants",
    "He who fears death will never do anything worthy",
    "What stands in the way becomes the way",
    "Receive without pride, let go without attachment",
    "Think of yourself as dead. Now live the rest properly.",
    "A gem cannot be polished without friction",
    "Life is long enough if you know how to use it",
    "Be tolerant with others, strict with yourself",
    "Choose not to be harmed, and you won't be",
    "Every new beginning comes from another's end",
    "If it is not right, do not do it",
    "Look inward. The source of good is there.",
    "Nothing is more honorable than a grateful heart",
    "Don't seek for things to happen as you wish",
    "Do what you must, as a human, now",
    "Time is the one thing we cannot recover",
    "Man is disturbed by his view of things",
    "Cease to hope, and you will cease to fear",
    "Better to trip with the feet than the tongue",
    "You are a small part. Play your part well.",
    "Fate leads the willing and drags the unwilling",
    "Curb your desire; don't set your heart on many things",
    "Hang on to your youthful enthusiasms",
    "The whole future lies in uncertainty. Live now.",
    "What we do now echoes in eternity",
    "Say little, and do much",
    "Loss is nothing but change",
    "Accept whatever comes woven into your thread",
    "You could leave life right now. Let that decide.",
    "Anger is a brief madness",
    "To be calm is the greatest privilege",
    "Practice poverty now and then, to know it holds no fear",
    "Character is fate",
    "Doing nothing is also a choice",
    "When you wake, think what a privilege it is to be alive",
  ],
};
