export default {
  name: "wholesome",
  title: "Wholesome",
  emoji: "💖",
  lang: "en",
  description: "Gentle, kind messages for your profile visitors.",
  kind: "rotating",
  messages: [
    "You're doing better than you think",
    "Someone is glad you exist",
    "Drink some water. You deserve it.",
    "Have you stretched today?",
    "Your work matters, even the quiet parts",
    "Take the break. The code will wait.",
    "Thank you for being here",
    "Be kind to the version of you that's tired",
    "You are allowed to rest",
    "You made it to today. That counts.",
    "Sending a virtual high five ✋",
    "Somebody learned from something you wrote",
    "Your curiosity is a gift",
    "Small kindnesses ripple",
    "Go outside for five minutes. Trust me.",
    "You don't have to earn rest",
    "Hi, stranger. Hope your day is soft.",
    "Compliment someone today",
    "You're allowed to change your mind",
    "It's okay to not know yet",
    "Be as patient with yourself as with a friend",
    "Your effort is visible, even if quiet",
    "A good sleep fixes more than you'd expect",
    "Nobody has it all figured out",
    "Keep a list of things that went right",
    "Proud of you for showing up",
    "You're someone's favourite person",
    "Eat something green today 🥦",
    "Thanks for reading this far",
    "Hug a pet, or a plant, or a pillow",
    "You have more time than you fear",
    "Unclench your jaw. Drop your shoulders.",
    "The world is better with you in it",
    "Your best is enough",
    "Say the nice thing out loud",
    "Text someone you've been meaning to",
    "Slow mornings are underrated",
    "Not every day needs to be productive",
    "Celebrate the tiny wins",
    "Whatever today brings, you've got this",
    "You are not behind. You're on your path.",
    "Kindness costs nothing and compounds",
    "It's a good day to forgive yourself",
    "Rest, hydrate, repeat",
    "You are enough, exactly as you are",
    "The best is still ahead of you",
    "Wave at a dog today",
    "Thank you for the work you do",
    "Breathe in for four, out for six",
    "Welcome! Make yourself at home.",
  ],
};
